### ISSUE TITLE
gunicorn/eventlet/nginx config 

### ISSUE THREAD

**Issue by nikitph** [level09/enferno-ansible#1]
great stuff with enferno man. this is not a issue but more of a request. do you have any pointers to tuning ansible config for enferno/flask-socketio/nginx/gunicorn/eventlet?

**Comment by level09** [comment]
Hi @nikitph, 

Nginx is automatically setup with this playbook. 

You can change the worker type in https://github.com/level09/enferno-ansible/blob/master/roles/enferno/templates/enferno.sh#L14

You can specify different worker types for Gunicorn by passing -k gevent or -k sync 

if you want to use websockets I recommend using this library:
https://github.com/zeekay/flask-uwsgi-websocket
and deploying your app with uwsgi. 

Hope that helps

**Comment by nikitph** [comment]
thanks a lot
